accounts=["3f093fed33d7","23a3e456fc2f"]
rpc="http://0.0.0.0:8888"

[api]
sms="发短信接口地址"
mail="发邮件接口地址"
walletInfo="账号资产信息接口地址"
transfer="账号充值接口地址"

[receipts]
sms=["13858075274","15907332188"] #短信通知用户列表
mail=["hxz@disanbo.com","sss@dds.com"] #邮件通知用户列表

[charges]
    [charges.CNY]
    coinId=1
    minActiveAllowed=5     #最低阈值
    rechargeAmount=100     #每次充值数量
    maxRechargeTimes=2     #每天最多充值次数

    [charges.BTC]
    coinId=2
    minActiveAllowed=100  
    rechargeAmount=1000        
    maxRechargeTimes=2

    [charges.BTY]
    coinId=3
    minActiveAllowed=100  
    rechargeAmount=1000        
    maxRechargeTimes=2

    [charges.ETH]
    coinId=4
    minActiveAllowed=100  
    rechargeAmount=1000        
    maxRechargeTimes=2

    [charges.ETC]
    coinId=5
    minActiveAllowed=100  
    rechargeAmount=1000        
    maxRechargeTimes=2

    [charges.SC]
    coinId=7
    minActiveAllowed=100  
    rechargeAmount=1000        
    maxRechargeTimes=2

    [charges.ZEC]
    coinId=8
    minActiveAllowed=100  
    rechargeAmount=1000        
    maxRechargeTimes=2

    [charges.BTS]
    coinId=9
    minActiveAllowed=100  
    rechargeAmount=1000        
    maxRechargeTimes=2

    [charges.LTC]
    coinId=10
    minActiveAllowed=100  
    rechargeAmount=1000        
    maxRechargeTimes=2

    [charges.BCC]
    coinId=11
    minActiveAllowed=100  
    rechargeAmount=1000        
    maxRechargeTimes=2

    [charges.USDT]
    coinId=15
    minActiveAllowed=100  
    rechargeAmount=1000        
    maxRechargeTimes=2

    [charges.DCR]
    coinId=17
    minActiveAllowed=100  
    rechargeAmount=1000        
    maxRechargeTimes=2