accounts=3f093fed33d7,23a3e456fc2f
rpc=http://0.0.0.0:8888

[api]
sms=发短信接口地址
mail=发邮件接口地址
walletInfo=账号资产信息接口地址
transfer=账号充值接口地址

[sms]
receipts=13858075274,15907332188 #短信通知用户列表

[email]
receipts=hxz@disanbo.com,sss@dds.com   #邮件通知用户列表

[BTC]
minActiveAllowed=5     #最低阈值
rechargeAmount=100     #每次充值数量
maxRechargeTimes=2     #每天最多充值次数

[USDT]
minActiveAllowed=100  
rechargeAmount=1000        
maxRechargeTimes=2

#币种代号信息
[coin]
CNY=1
BTC=2
BTY=3
ETH=4
ETC=5
USD=6
SC=7
ZEC=8
BTS=9
LTC=10
BCC=11
YCC=12
NYCC=13
WTC=14
USDT=15
BTCS=16
DCR=17
